.TH "__alooLabel" 3 "Sun Sep 1 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__alooLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <label\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB_newLabelType\fP \fBnew\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB_newLabelType\fP __alooLabel::new"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
