.TH "_alooGrid" 3 "Sun Sep 1 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooGrid
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grid\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__gridAttach_Type\fP \fBattach\fP"
.br
.ti -1c
.RI "\fB__gridAttachGtk_Type\fP \fBattachGtk\fP"
.br
.ti -1c
.RI "\fB__gridRemove_Type\fP \fBremove\fP"
.br
.ti -1c
.RI "\fB__gridRemoveGtk_Type\fP \fBremoveGtk\fP"
.br
.ti -1c
.RI "\fB__alooGridNew_Type\fP \fBnew\fP"
.br
.ti -1c
.RI "\fB__setGridColumnSpacing_Type\fP \fBcolumn_spacing\fP"
.br
.ti -1c
.RI "\fB__setGridRowSpacing_Type\fP \fBrow_spacing\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__gridAttach_Type\fP _alooGrid::attach"

.SS "\fB__gridAttachGtk_Type\fP _alooGrid::attachGtk"

.SS "\fB__setGridColumnSpacing_Type\fP _alooGrid::column_spacing"

.SS "\fB__alooGridNew_Type\fP _alooGrid::new"

.SS "\fB__gridRemove_Type\fP _alooGrid::remove"

.SS "\fB__gridRemoveGtk_Type\fP _alooGrid::removeGtk"

.SS "\fB__setGridRowSpacing_Type\fP _alooGrid::row_spacing"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
