.TH "_aloo_widget" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_aloo_widget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <widget\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GtkWidget *(* \fBobj_to_gtk\fP )(\fBAlooBuilder\fP *builder, const char *name)"
.br
.RI "Creates GtkWidget from builder\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBobj_to_aloo\fP )(GObject *obj)"
.br
.RI "Create \fBalooWidget\fP from GObject\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBgtk_to_aloo\fP )(GtkWidget *widget)"
.br
.RI "Creates \fBalooWidget\fP from GtkWidget\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetOrientation\fP )(\fBalooWidget\fP *widget, GtkOrientation orien)"
.br
.RI "Sets orientation of \fBalooWidget\fP\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBnew\fP )(\fBWidgetType\fP type, GtkWidget *child)"
.br
.RI "Create a widget\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetName\fP )(\fBalooWidget\fP *widget, const char *name)"
.br
.RI "Set the Name of widget\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBhorizontalAlign\fP )(\fBalooWidget\fP *widget, GtkAlign alignment)"
.br
.RI "Sets horizontal alignment of \fBalooWidget\fP\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBverticalAlign\fP )(\fBalooWidget\fP *widget, GtkAlign alignment)"
.br
.RI "Sets vertical alignment of \fBalooWidget\fP\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBaddEventListener\fP )(\fBalooWidget\fP *widget_instance, char *event_name, GCallback CallbackFn, gpointer data)"
.br
.RI "Adds event listener to a widget\&. "
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int(* \fBisBox\fP )(\fBalooWidget\fP *wid)"
.br
.ti -1c
.RI "   int(* \fBisButton\fP )(\fBalooWidget\fP *wid)"
.br
.ti -1c
.RI "   int(* \fBisGrid\fP )(\fBalooWidget\fP *wid)"
.br
.ti -1c
.RI "   int(* \fBisLabel\fP )(\fBalooWidget\fP *wid)"
.br
.ti -1c
.RI "   int(* \fBisWindow\fP )(\fBalooWidget\fP *wid)"
.br
.ti -1c
.RI "} \fBcheck\fP"
.br
.ti -1c
.RI "GtkWidget *(* \fBto_gtk\fP )(\fBalooWidget\fP *wid)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBalooWidget\fP*(* _aloo_widget::addEventListener) (\fBalooWidget\fP *widget_instance, char *event_name, GCallback CallbackFn, gpointer data)"

.PP
Adds event listener to a widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidget_instance\fP 
.br
\fIdata\fP parameters for event listener 
.RE
.PP

.SS "struct { \&.\&.\&. }  _aloo_widget::check"

.SS "\fBalooWidget\fP*(* _aloo_widget::gtk_to_aloo) (GtkWidget *widget)"

.PP
Creates \fBalooWidget\fP from GtkWidget\&. 
.SS "\fBalooWidget\fP*(* _aloo_widget::horizontalAlign) (\fBalooWidget\fP *widget, GtkAlign alignment)"

.PP
Sets horizontal alignment of \fBalooWidget\fP\&. 
.SS "int(* _aloo_widget::isBox) (\fBalooWidget\fP *wid)"

.SS "int(* _aloo_widget::isButton) (\fBalooWidget\fP *wid)"

.SS "int(* _aloo_widget::isGrid) (\fBalooWidget\fP *wid)"

.SS "int(* _aloo_widget::isLabel) (\fBalooWidget\fP *wid)"

.SS "int(* _aloo_widget::isWindow) (\fBalooWidget\fP *wid)"

.SS "\fBalooWidget\fP*(* _aloo_widget::new) (\fBWidgetType\fP type, GtkWidget *child)"

.PP
Create a widget\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP type of widget 
.br
\fIchild\fP actual GtkWidget 
.RE
.PP
\fBReturns\fP
.RS 4
alooWidget* 
.RE
.PP

.SS "\fBalooWidget\fP*(* _aloo_widget::obj_to_aloo) (GObject *obj)"

.PP
Create \fBalooWidget\fP from GObject\&. 
.SS "GtkWidget*(* _aloo_widget::obj_to_gtk) (\fBAlooBuilder\fP *builder, const char *name)"

.PP
Creates GtkWidget from builder\&. 
.SS "\fBalooWidget\fP*(* _aloo_widget::setName) (\fBalooWidget\fP *widget, const char *name)"

.PP
Set the Name of widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidget\fP \fBalooWidget\fP 
.br
\fIname\fP string for name of widget 
.RE
.PP
\fBReturns\fP
.RS 4
returns the widget 
.RE
.PP

.SS "\fBalooWidget\fP*(* _aloo_widget::setOrientation) (\fBalooWidget\fP *widget, GtkOrientation orien)"

.PP
Sets orientation of \fBalooWidget\fP\&. 
.SS "GtkWidget*(* _aloo_widget::to_gtk) (\fBalooWidget\fP *wid)"

.SS "\fBalooWidget\fP*(* _aloo_widget::verticalAlign) (\fBalooWidget\fP *widget, GtkAlign alignment)"

.PP
Sets vertical alignment of \fBalooWidget\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
