.TH "_alooButton" 3 "Sat Aug 31 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <button\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__newButton_Type\fP \fBnew\fP"
.br
.RI "Creates new Aloo Button without label\&. "
.ti -1c
.RI "\fB__newButtonWithLabel_Type\fP \fBnewWithLabel\fP"
.br
.RI "Creates new Aloo Button with label\&. "
.ti -1c
.RI "\fB__setLabel_Type\fP \fBlabel\fP"
.br
.RI "Sets the label of the button\&. "
.ti -1c
.RI "\fB__setChild_Type\fP \fBchild\fP"
.br
.RI "Sets the child of the button\&. "
.ti -1c
.RI "\fB__setIcon_Type\fP \fBicon\fP"
.br
.RI "Sets the icon of the button\&. "
.ti -1c
.RI "\fB__setUseUnderline_Type\fP \fBuseUnderline\fP"
.br
.RI "Sets whether to use underline or not in the button\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__setChild_Type\fP _alooButton::child"

.PP
Sets the child of the button\&. 
.SS "\fB__setIcon_Type\fP _alooButton::icon"

.PP
Sets the icon of the button\&. 
.SS "\fB__setLabel_Type\fP _alooButton::label"

.PP
Sets the label of the button\&. 
.SS "\fB__newButton_Type\fP _alooButton::new"

.PP
Creates new Aloo Button without label\&. 
.SS "\fB__newButtonWithLabel_Type\fP _alooButton::newWithLabel"

.PP
Creates new Aloo Button with label\&. 
.SS "\fB__setUseUnderline_Type\fP _alooButton::useUnderline"

.PP
Sets whether to use underline or not in the button\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
