.TH "_alooCSS" 3 "Sun Sep 1 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooCSS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <style\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__importCssFromPath_Type\fP \fBimportPath\fP"
.br
.ti -1c
.RI "\fB__importCssFromData_Type\fP \fBimportData\fP"
.br
.ti -1c
.RI "\fB__importCssFromFile_Type\fP \fBimportFile\fP"
.br
.ti -1c
.RI "\fB__setWidth_Type\fP \fBsetWidth\fP"
.br
.ti -1c
.RI "\fB__setHeight_Type\fP \fBsetHeight\fP"
.br
.ti -1c
.RI "\fB__setSize_Type\fP \fBsetSize\fP"
.br
.ti -1c
.RI "\fB__widgetAddClass_Type\fP \fBaddClass\fP"
.br
.ti -1c
.RI "\fB__widgetRemoveClass_Type\fP \fBremoveClass\fP"
.br
.ti -1c
.RI "\fB__getWidgetClasses_Type\fP \fBgetClasses\fP"
.br
.ti -1c
.RI "\fB__setWidgetClasses_Type\fP \fBsetClasses\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__widgetAddClass_Type\fP _alooCSS::addClass"

.SS "\fB__getWidgetClasses_Type\fP _alooCSS::getClasses"

.SS "\fB__importCssFromData_Type\fP _alooCSS::importData"

.SS "\fB__importCssFromFile_Type\fP _alooCSS::importFile"

.SS "\fB__importCssFromPath_Type\fP _alooCSS::importPath"

.SS "\fB__widgetRemoveClass_Type\fP _alooCSS::removeClass"

.SS "\fB__setWidgetClasses_Type\fP _alooCSS::setClasses"

.SS "\fB__setHeight_Type\fP _alooCSS::setHeight"

.SS "\fB__setSize_Type\fP _alooCSS::setSize"

.SS "\fB__setWidth_Type\fP _alooCSS::setWidth"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
