.TH "_alooBox" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooBox
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <box\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBalooWidget\fP *(* \fBnew\fP )(GtkOrientation orientation, int spacing)"
.br
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetOrientation\fP )(\fBalooWidget\fP *box, GtkOrientation orientation)"
.br
.ti -1c
.RI "GtkOrientation(* \fBgetOrientation\fP )(\fBalooWidget\fP *box)"
.br
.RI "Gets Box Orientation\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBappendGtk\fP )(\fBalooWidget\fP *box, GtkWidget *widget)"
.br
.RI "Appends \fCGtkWidget\fP child to box\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBprependGtk\fP )(\fBalooWidget\fP *box, GtkWidget *widget)"
.br
.RI "Prepends \fCGtkWidget\fP child to box\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBremoveGtk\fP )(\fBalooWidget\fP *box, GtkWidget *widget)"
.br
.RI "Removes \fCGtkWidget\fP child from box\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBappend\fP )(\fBalooWidget\fP *box, \fBalooWidget\fP *widget)"
.br
.RI "Appends \fC\fBalooWidget\fP\fP child to box\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBprepend\fP )(\fBalooWidget\fP *box, \fBalooWidget\fP *widget)"
.br
.RI "Prepends \fC\fBalooWidget\fP\fP child to box\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBremove\fP )(\fBalooWidget\fP *box, \fBalooWidget\fP *widget)"
.br
.RI "Removes \fC\fBalooWidget\fP\fP child from box\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBinsertChildAfter\fP )(\fBalooWidget\fP *box, \fBalooWidget\fP *child, \fBalooWidget\fP *after)"
.br
.RI "Adds child after a certain widget of box\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetSpacing\fP )(\fBalooWidget\fP *box, int spacing)"
.br
.RI "Sets Box Spacing\&. "
.ti -1c
.RI "int(* \fBgetSpacing\fP )(\fBalooWidget\fP *box)"
.br
.RI "Gets Box Spacing\&. "
.ti -1c
.RI "gboolean(* \fBgetHomogeneous\fP )(\fBalooWidget\fP *box)"
.br
.RI "Gets box homogeneous\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetHomogeneous\fP )(\fBalooWidget\fP *box, gboolean homogeneous)"
.br
.RI "Sets box homogeneous\&. "
.ti -1c
.RI "GtkBaselinePosition(* \fBgetBaselinePosition\fP )(\fBalooWidget\fP *box)"
.br
.RI "Gets Box baseline position\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetBaselinePosition\fP )(\fBalooWidget\fP *box, GtkBaselinePosition position)"
.br
.RI "Sets Box baseline position\&. "
.ti -1c
.RI "GtkBox *(* \fBtoGtk\fP )(\fBalooWidget\fP *widget)"
.br
.RI "Returns Gtk Box\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBalooWidget\fP*(* _alooBox::append) (\fBalooWidget\fP *box, \fBalooWidget\fP *widget)"

.PP
Appends \fC\fBalooWidget\fP\fP child to box\&. 
.SS "\fBalooWidget\fP*(* _alooBox::appendGtk) (\fBalooWidget\fP *box, GtkWidget *widget)"

.PP
Appends \fCGtkWidget\fP child to box\&. 
.SS "GtkBaselinePosition(* _alooBox::getBaselinePosition) (\fBalooWidget\fP *box)"

.PP
Gets Box baseline position\&. 
.SS "gboolean(* _alooBox::getHomogeneous) (\fBalooWidget\fP *box)"

.PP
Gets box homogeneous\&. 
.SS "GtkOrientation(* _alooBox::getOrientation) (\fBalooWidget\fP *box)"

.PP
Gets Box Orientation\&. 
.SS "int(* _alooBox::getSpacing) (\fBalooWidget\fP *box)"

.PP
Gets Box Spacing\&. 
.SS "\fBalooWidget\fP*(* _alooBox::insertChildAfter) (\fBalooWidget\fP *box, \fBalooWidget\fP *child, \fBalooWidget\fP *after)"

.PP
Adds child after a certain widget of box\&. 
.PP
\fBReturns\fP
.RS 4
returns box 
.RE
.PP

.SS "\fBalooWidget\fP*(* _alooBox::new) (GtkOrientation orientation, int spacing)"

.SS "\fBalooWidget\fP*(* _alooBox::prepend) (\fBalooWidget\fP *box, \fBalooWidget\fP *widget)"

.PP
Prepends \fC\fBalooWidget\fP\fP child to box\&. 
.SS "\fBalooWidget\fP*(* _alooBox::prependGtk) (\fBalooWidget\fP *box, GtkWidget *widget)"

.PP
Prepends \fCGtkWidget\fP child to box\&. 
.SS "\fBalooWidget\fP*(* _alooBox::remove) (\fBalooWidget\fP *box, \fBalooWidget\fP *widget)"

.PP
Removes \fC\fBalooWidget\fP\fP child from box\&. 
.SS "\fBalooWidget\fP*(* _alooBox::removeGtk) (\fBalooWidget\fP *box, GtkWidget *widget)"

.PP
Removes \fCGtkWidget\fP child from box\&. 
.SS "\fBalooWidget\fP*(* _alooBox::setBaselinePosition) (\fBalooWidget\fP *box, GtkBaselinePosition position)"

.PP
Sets Box baseline position\&. 
.SS "\fBalooWidget\fP*(* _alooBox::setHomogeneous) (\fBalooWidget\fP *box, gboolean homogeneous)"

.PP
Sets box homogeneous\&. 
.SS "\fBalooWidget\fP*(* _alooBox::setOrientation) (\fBalooWidget\fP *box, GtkOrientation orientation)"

.SS "\fBalooWidget\fP*(* _alooBox::setSpacing) (\fBalooWidget\fP *box, int spacing)"

.PP
Sets Box Spacing\&. 
.SS "GtkBox*(* _alooBox::toGtk) (\fBalooWidget\fP *widget)"

.PP
Returns Gtk Box\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
