.TH "_alooWindow" 3 "Sun Sep 1 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__alooApplicationNewWindow_Type\fP \fBnew\fP"
.br
.ti -1c
.RI "\fB__alooPresentWindow_Type\fP \fBpresent\fP"
.br
.ti -1c
.RI "\fB__alooSetWindowChild_Type\fP \fBsetChild\fP"
.br
.ti -1c
.RI "\fB__alooSetWindowTitle_Type\fP \fBsetTitle\fP"
.br
.ti -1c
.RI "\fB__setWindowSize_Type\fP \fBsetSize\fP"
.br
.ti -1c
.RI "\fB__setWindowApplication_Type\fP \fBset_app_window\fP"
.br
.ti -1c
.RI "\fB__app_add_window_Type\fP \fBapp_add_window\fP"
.br
.ti -1c
.RI "\fB__showWindow_Type\fP \fBshow\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__app_add_window_Type\fP _alooWindow::app_add_window"

.SS "\fB__alooApplicationNewWindow_Type\fP _alooWindow::new"

.SS "\fB__alooPresentWindow_Type\fP _alooWindow::present"

.SS "\fB__setWindowApplication_Type\fP _alooWindow::set_app_window"

.SS "\fB__alooSetWindowChild_Type\fP _alooWindow::setChild"

.SS "\fB__setWindowSize_Type\fP _alooWindow::setSize"

.SS "\fB__alooSetWindowTitle_Type\fP _alooWindow::setTitle"

.SS "\fB__showWindow_Type\fP _alooWindow::show"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
