.TH "_alooButton" 3 "Tue Sep 3 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <button\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBalooWidget\fP *(* \fBnew\fP )()"
.br
.RI "Creates new Aloo Button without label\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBnewWithLabel\fP )(const char *\fBlabel\fP)"
.br
.RI "Creates new Aloo Button with label\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBlabel\fP )(\fBalooWidget\fP *btn, char const *name)"
.br
.RI "Sets the label of the button\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBchild\fP )(\fBalooWidget\fP *btn, \fBalooWidget\fP *child)"
.br
.RI "Sets the child of the button\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBicon\fP )(\fBalooWidget\fP *btn, const char *\fBchild\fP)"
.br
.RI "Sets the icon of the button\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBuseUnderline\fP )(\fBalooWidget\fP *btn, gboolean yes)"
.br
.RI "Sets whether to use underline or not in the button\&. "
.ti -1c
.RI "GtkButton *(* \fBtoGtk\fP )(\fBalooWidget\fP *wid)"
.br
.RI "Converts Aloo Button to Gtk Button\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBalooWidget\fP*(* _alooButton::child) (\fBalooWidget\fP *btn, \fBalooWidget\fP *child)"

.PP
Sets the child of the button\&. 
.SS "\fBalooWidget\fP*(* _alooButton::icon) (\fBalooWidget\fP *btn, const char *\fBchild\fP)"

.PP
Sets the icon of the button\&. 
.SS "\fBalooWidget\fP*(* _alooButton::label) (\fBalooWidget\fP *btn, char const *name)"

.PP
Sets the label of the button\&. 
.SS "\fBalooWidget\fP*(* _alooButton::new) ()"

.PP
Creates new Aloo Button without label\&. 
.SS "\fBalooWidget\fP*(* _alooButton::newWithLabel) (const char *\fBlabel\fP)"

.PP
Creates new Aloo Button with label\&. 
.SS "GtkButton*(* _alooButton::toGtk) (\fBalooWidget\fP *wid)"

.PP
Converts Aloo Button to Gtk Button\&. 
.SS "\fBalooWidget\fP*(* _alooButton::useUnderline) (\fBalooWidget\fP *btn, gboolean yes)"

.PP
Sets whether to use underline or not in the button\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
