.TH "_alooWindow" 3 "Tue Sep 3 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBalooWidget\fP *(* \fBnew\fP )(\fBAlooApplication\fP *app)"
.br
.RI "Create a GtkWindow\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBpresent\fP )(\fBalooWidget\fP *window)"
.br
.RI "Presents GtkWindow\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetChild\fP )(\fBalooWidget\fP *window, \fBalooWidget\fP *child)"
.br
.RI "Sets Window child\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetTitle\fP )(\fBalooWidget\fP *window, const char *title)"
.br
.RI "Sets GtkWindow title\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBsetSize\fP )(\fBalooWidget\fP *window, int width, int height)"
.br
.RI "Sets aloo Window size\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBset_app_window\fP )(\fBalooWidget\fP *window, \fBAlooApplication\fP *app)"
.br
.RI "Set the Window for Application\&. "
.ti -1c
.RI "\fBalooWidget\fP *(* \fBapp_add_window\fP )(\fBAlooApplication\fP *app, \fBalooWidget\fP *window)"
.br
.RI "Adds Window to Application\&. "
.ti -1c
.RI "void(* \fBshow\fP )(\fBalooWidget\fP *window)"
.br
.RI "Shows Window\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBalooWidget\fP*(* _alooWindow::app_add_window) (\fBAlooApplication\fP *app, \fBalooWidget\fP *window)"

.PP
Adds Window to Application\&. 
.PP
\fBParameters\fP
.RS 4
\fIapp\fP AlooApplication* 
.br
\fIwindow\fP alooWidget* 
.RE
.PP
\fBReturns\fP
.RS 4
aloowidget* 
.RE
.PP

.SS "\fBalooWidget\fP*(* _alooWindow::new) (\fBAlooApplication\fP *app)"

.PP
Create a GtkWindow\&. 
.PP
\fBParameters\fP
.RS 4
\fIapp\fP AlooApplication* 
.RE
.PP
\fBReturns\fP
.RS 4
alooWidget* 
.RE
.PP

.SS "\fBalooWidget\fP*(* _alooWindow::present) (\fBalooWidget\fP *window)"

.PP
Presents GtkWindow\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP alooWidget* 
.RE
.PP
\fBReturns\fP
.RS 4
alooWidget* 
.RE
.PP

.SS "\fBalooWidget\fP*(* _alooWindow::set_app_window) (\fBalooWidget\fP *window, \fBAlooApplication\fP *app)"

.PP
Set the Window for Application\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP alooWidget* 
.br
\fIapp\fP AlooApplication* 
.RE
.PP
\fBReturns\fP
.RS 4
alooWidget* 
.RE
.PP

.SS "\fBalooWidget\fP*(* _alooWindow::setChild) (\fBalooWidget\fP *window, \fBalooWidget\fP *child)"

.PP
Sets Window child\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP \fBalooWidget\fP * 
.br
\fIchild\fP \fBalooWidget\fP * 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "\fBalooWidget\fP*(* _alooWindow::setSize) (\fBalooWidget\fP *window, int width, int height)"

.PP
Sets aloo Window size\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP \fBalooWidget\fP * 
.br
\fIwidth\fP int 
.br
\fIheight\fP int 
.RE
.PP
\fBReturns\fP
.RS 4
alooWidget* 
.RE
.PP

.SS "\fBalooWidget\fP*(* _alooWindow::setTitle) (\fBalooWidget\fP *window, const char *title)"

.PP
Sets GtkWindow title\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP \fBalooWidget\fP * 
.br
\fItitle\fP const char* 
.RE
.PP
\fBReturns\fP
.RS 4
\fBalooWidget\fP * 
.RE
.PP

.SS "void(* _alooWindow::show) (\fBalooWidget\fP *window)"

.PP
Shows Window\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP alooWidget* 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
