.TH "_alooBox" 3 "Sun Sep 1 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_alooBox
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <box\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__new_alooBox_Type\fP \fBnew\fP"
.br
.ti -1c
.RI "\fB__setBoxOrientation_Type\fP \fBsetOrientation\fP"
.br
.ti -1c
.RI "\fB__getBoxOrientation_Type\fP \fBgetOrientation\fP"
.br
.ti -1c
.RI "\fB__boxAppendGtk_Type\fP \fBappendGtk\fP"
.br
.ti -1c
.RI "\fB__boxPrependGtk_Type\fP \fBprependGtk\fP"
.br
.ti -1c
.RI "\fB__boxRemoveGtk_Type\fP \fBremoveGtk\fP"
.br
.ti -1c
.RI "\fB__boxAppend_Type\fP \fBappend\fP"
.br
.ti -1c
.RI "\fB__boxPrepend_Type\fP \fBprepend\fP"
.br
.ti -1c
.RI "\fB__boxRemove_Type\fP \fBremove\fP"
.br
.ti -1c
.RI "\fB__boxInsertChildAfter_Type\fP \fBinsertChildAfter\fP"
.br
.ti -1c
.RI "\fB__setBoxSpacing_Type\fP \fBsetSpacing\fP"
.br
.ti -1c
.RI "\fB__getBoxSpacing_Type\fP \fBgetSpacing\fP"
.br
.ti -1c
.RI "\fB__getBoxHomogeneous_Type\fP \fBgetHomogeneous\fP"
.br
.ti -1c
.RI "\fB__setBoxHomogeneous_Type\fP \fBsetHomogeneous\fP"
.br
.ti -1c
.RI "\fB__getBoxBaselinePosition_Type\fP \fBgetBaselinePosition\fP"
.br
.ti -1c
.RI "\fB__setBoxBaselinePosition_Type\fP \fBsetBaselinePosition\fP"
.br
.ti -1c
.RI "\fB__toGtk_Type\fP \fBtoGtk\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__boxAppend_Type\fP _alooBox::append"

.SS "\fB__boxAppendGtk_Type\fP _alooBox::appendGtk"

.SS "\fB__getBoxBaselinePosition_Type\fP _alooBox::getBaselinePosition"

.SS "\fB__getBoxHomogeneous_Type\fP _alooBox::getHomogeneous"

.SS "\fB__getBoxOrientation_Type\fP _alooBox::getOrientation"

.SS "\fB__getBoxSpacing_Type\fP _alooBox::getSpacing"

.SS "\fB__boxInsertChildAfter_Type\fP _alooBox::insertChildAfter"

.SS "\fB__new_alooBox_Type\fP _alooBox::new"

.SS "\fB__boxPrepend_Type\fP _alooBox::prepend"

.SS "\fB__boxPrependGtk_Type\fP _alooBox::prependGtk"

.SS "\fB__boxRemove_Type\fP _alooBox::remove"

.SS "\fB__boxRemoveGtk_Type\fP _alooBox::removeGtk"

.SS "\fB__setBoxBaselinePosition_Type\fP _alooBox::setBaselinePosition"

.SS "\fB__setBoxHomogeneous_Type\fP _alooBox::setHomogeneous"

.SS "\fB__setBoxOrientation_Type\fP _alooBox::setOrientation"

.SS "\fB__setBoxSpacing_Type\fP _alooBox::setSpacing"

.SS "\fB__toGtk_Type\fP _alooBox::toGtk"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
