.TH "include/builtin Directory Reference" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/builtin Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapp\&.h\fP"
.br
.RI "Aloo Application related functions\&. "
.ti -1c
.RI "file \fBbox\&.h\fP"
.br
.RI "Aloo Box functions\&. "
.ti -1c
.RI "file \fBbuilder\&.h\fP"
.br
.RI "This file contains UI Builder related functions\&. "
.ti -1c
.RI "file \fBbutton\&.h\fP"
.br
.RI "Aloo Button related functions\&. "
.ti -1c
.RI "file \fBgrid\&.h\fP"
.br
.RI "Aloo Grid related functions\&. "
.ti -1c
.RI "file \fBlabel\&.h\fP"
.br
.RI "Aloo Label related functions\&. "
.ti -1c
.RI "file \fBmacros\&.h\fP"
.br
.RI "Aloo Project Macros related functions\&. "
.ti -1c
.RI "file \fBstyle\&.h\fP"
.br
.RI "Aloo CSS related functions\&. "
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.RI "Aloo Project Types related functions\&. "
.ti -1c
.RI "file \fBwidget\&.h\fP"
.br
.RI "Aloo Widget related functions\&. "
.ti -1c
.RI "file \fBwindow\&.h\fP"
.br
.RI "Contains aloo Window related functions\&. "
.in -1c
