.TH "include Directory Reference" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbuiltin\fP"
.br
.ti -1c
.RI "directory \fBtest\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaloo\&.h\fP"
.br
.RI "Aloo Project Main file It conatins all the header files\&. "
.in -1c
