.TH "_Test" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Test
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aloo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBexpectInt\fP )(int expected, int actual)"
.br
.ti -1c
.RI "int(* \fBexpectWidget\fP )(\fBalooWidget\fP *expected, \fBalooWidget\fP *actual)"
.br
.ti -1c
.RI "int(* \fBexpectGtkWidget\fP )(GtkWidget *expected, \fBalooWidget\fP *actual)"
.br
.ti -1c
.RI "void(* \fBaddTest\fP )(const char *test_name, struct \fB_Test\fP *test, int test_res)"
.br
.ti -1c
.RI "void(* \fBresult\fP )(struct \fB_Test\fP *t)"
.br
.ti -1c
.RI "int \fBtestCount\fP"
.br
.ti -1c
.RI "int \fBtestPassed\fP"
.br
.ti -1c
.RI "int \fBtestFailed\fP"
.br
.ti -1c
.RI "const char * \fBlabel\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void(* _Test::addTest) (const char *test_name, struct \fB_Test\fP *test, int test_res)"

.SS "int(* _Test::expectGtkWidget) (GtkWidget *expected, \fBalooWidget\fP *actual)"

.SS "int(* _Test::expectInt) (int expected, int actual)"

.SS "int(* _Test::expectWidget) (\fBalooWidget\fP *expected, \fBalooWidget\fP *actual)"

.SS "const char* _Test::label"

.SS "void(* _Test::result) (struct \fB_Test\fP *t)"

.SS "int _Test::testCount"

.SS "int _Test::testFailed"

.SS "int _Test::testPassed"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
