.TH "alooWidget" 3 "Thu Aug 29 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alooWidget \- widget for my aloo library  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GtkWidget * \fBchild\fP"
.br
.RI "actual GtkWidget "
.ti -1c
.RI "\fBWidgetType\fP \fBtype\fP"
.br
.RI "Type of widget\&. "
.in -1c
.SH "Detailed Description"
.PP 
widget for my aloo library 
.SH "Member Data Documentation"
.PP 
.SS "GtkWidget* alooWidget::child"

.PP
actual GtkWidget 
.SS "\fBWidgetType\fP alooWidget::type"

.PP
Type of widget\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
