.TH "alooAppAndStatus" 3 "Thu Aug 29 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alooAppAndStatus \- Returns GtkApplication and status\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <app\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GtkApplication * \fBapp\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Returns GtkApplication and status\&. 
.SH "Member Data Documentation"
.PP 
.SS "GtkApplication* alooAppAndStatus::app"

.SS "int alooAppAndStatus::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
