.TH "AlooApplication" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlooApplication
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <app\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GtkApplication * \fBapp\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GtkApplication* AlooApplication::app"

.SS "int AlooApplication::argc"

.SS "char** AlooApplication::argv"

.SS "int AlooApplication::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
