.TH "alooAppOptions" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alooAppOptions \- Takes GApplicationFlags, argc and argv\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <app\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBalooAppFlags\fP \fBappFlags\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Takes GApplicationFlags, argc and argv\&. 
.SH "Member Data Documentation"
.PP 
.SS "enum \fBalooAppFlags\fP alooAppOptions::appFlags"

.SS "int alooAppOptions::argc"

.SS "char** alooAppOptions::argv"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
