.TH "AlooBuilder" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlooBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GtkBuilder * \fBbuilder\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GtkBuilder* AlooBuilder::builder"


.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
