.TH "include/aloo.h" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/aloo.h \- Aloo Project Main file It conatins all the header files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'app\&.h'\fP
.br
\fC#include 'box\&.h'\fP
.br
\fC#include 'builder\&.h'\fP
.br
\fC#include 'button\&.h'\fP
.br
\fC#include 'grid\&.h'\fP
.br
\fC#include 'label\&.h'\fP
.br
\fC#include 'macros\&.h'\fP
.br
\fC#include 'style\&.h'\fP
.br
\fC#include 'utils/error\&.h'\fP
.br
\fC#include 'utils/logger\&.h'\fP
.br
\fC#include 'widget\&.h'\fP
.br
\fC#include 'window\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Aloo Project Main file It conatins all the header files\&. 


.PP
\fBAuthor\fP
.RS 4
Jaipal001 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
