.TH "include/aloo.h" 3 "Fri Aug 30 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/aloo.h
.SH SYNOPSIS
.br
.PP
\fC#include 'app\&.h'\fP
.br
\fC#include 'box\&.h'\fP
.br
\fC#include 'button\&.h'\fP
.br
\fC#include 'grid\&.h'\fP
.br
\fC#include 'label\&.h'\fP
.br
\fC#include 'style\&.h'\fP
.br
\fC#include 'widget\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
