.TH "include/app.h" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/app.h \- Aloo Application related functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br
\fC#include <gtk/gtk\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAlooApplication\fP"
.br
.ti -1c
.RI "struct \fBalooAppOptions\fP"
.br
.RI "Takes GApplicationFlags, argc and argv\&. "
.ti -1c
.RI "struct \fB_alooApp\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBAlooApplication\fP \fBAlooApplication\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBalooAppFlags\fP { \fBAPP_FLAGS_NONE\fP = 0, \fBAPP_FLAGS_IS_LAUNCHER\fP, \fBAPP_FLAGS_IS_SERVICE\fP }"
.br
.RI "G Application Flags\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAlooApplication\fP * \fB__CreateApp\fP (const char *app_id, struct \fBalooAppOptions\fP gAppOptions)"
.br
.RI "Create a App object\&. "
.ti -1c
.RI "int \fB__RunApp\fP (\fBAlooApplication\fP *application)"
.br
.RI "Runs aloo App\&. "
.ti -1c
.RI "int \fB__RunAppAndUnrefIt\fP (\fBAlooApplication\fP *application)"
.br
.RI "Runs aloo App and unrefs after exiting it\&. "
.ti -1c
.RI "void \fB__unrefApp\fP (\fBAlooApplication\fP *application)"
.br
.RI "unrefs aloo App "
.ti -1c
.RI "void \fB__AppAddEvents\fP (\fBAlooApplication\fP *app, const char *event, void callbackFn())"
.br
.RI "Adds Event Listener to Aloo App\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fB_alooApp\fP \fBApplication\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Aloo Application related functions\&. 


.PP
\fBAuthor\fP
.RS 4
Jaipal001 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBAlooApplication\fP \fBAlooApplication\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBalooAppFlags\fP"

.PP
G Application Flags\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAPP_FLAGS_NONE \fP\fP
G_APPLICATION_FLAGS_NONE\&. 
.TP
\fB\fIAPP_FLAGS_IS_LAUNCHER \fP\fP
G_APPLICATION_FLAGS_IS_LAUNCHER\&. 
.TP
\fB\fIAPP_FLAGS_IS_SERVICE \fP\fP
G_APPLICATION_FLAGS_IS_SERVICE\&. 
.SH "Function Documentation"
.PP 
.SS "void __AppAddEvents (\fBAlooApplication\fP * app, const char * event, void  callbackFn())"

.PP
Adds Event Listener to Aloo App\&. 
.PP
\fBParameters\fP
.RS 4
\fIapp\fP Aloo Application 
.br
\fIevent\fP Event name 
.br
\fIcallbackFn\fP static void function which will be called when app is started 
.RE
.PP

.SS "\fBAlooApplication\fP* __CreateApp (const char * app_id, struct \fBalooAppOptions\fP gAppOptions)"

.PP
Create a App object\&. 
.PP
\fBParameters\fP
.RS 4
\fIapp_id\fP App Id are like com\&.google\&.Chrome, dev\&.zed\&.Zed 
.br
\fIgAppOptions\fP It takes GApplicationFlags, argc and argv 
.RE
.PP
\fBReturns\fP
.RS 4
It returns Aloo Application 
.RE
.PP

.SS "int __RunApp (\fBAlooApplication\fP * application)"

.PP
Runs aloo App\&. 
.PP
\fBReturns\fP
.RS 4
status on exiting app 
.RE
.PP

.SS "int __RunAppAndUnrefIt (\fBAlooApplication\fP * application)"

.PP
Runs aloo App and unrefs after exiting it\&. 
.PP
\fBReturns\fP
.RS 4
status on exiting app 
.RE
.PP

.SS "void __unrefApp (\fBAlooApplication\fP * application)"

.PP
unrefs aloo App 
.SH "Variable Documentation"
.PP 
.SS "struct \fB_alooApp\fP Application\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
