.TH "include/builtin/button.h" 3 "Mon Sep 2 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/builtin/button.h \- Aloo Button related functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_alooButton\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBalooWidget\fP * \fB__newButton\fP ()"
.br
.ti -1c
.RI "\fBalooWidget\fP * \fB__newButtonWithLabel\fP (const char *label)"
.br
.ti -1c
.RI "\fBalooWidget\fP * \fB__setLabel\fP (\fBalooWidget\fP *btn, char const *name)"
.br
.ti -1c
.RI "\fBalooWidget\fP * \fB__setChild\fP (\fBalooWidget\fP *btn, \fBalooWidget\fP *child)"
.br
.ti -1c
.RI "\fBalooWidget\fP * \fB__setIcon\fP (\fBalooWidget\fP *btn, const char *child)"
.br
.ti -1c
.RI "\fBalooWidget\fP * \fB__setUseUnderline\fP (\fBalooWidget\fP *btn, gboolean yes)"
.br
.ti -1c
.RI "GtkButton * \fB__toButtonGtk\fP (\fBalooWidget\fP *wid)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fB_alooButton\fP \fBButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Aloo Button related functions\&. 


.PP
\fBAuthor\fP
.RS 4
Jaipal001 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBalooWidget\fP* __newButton ()"

.SS "\fBalooWidget\fP* __newButtonWithLabel (const char * label)"

.SS "\fBalooWidget\fP* __setChild (\fBalooWidget\fP * btn, \fBalooWidget\fP * child)"

.SS "\fBalooWidget\fP* __setIcon (\fBalooWidget\fP * btn, const char * child)"

.SS "\fBalooWidget\fP* __setLabel (\fBalooWidget\fP * btn, char const * name)"

.SS "\fBalooWidget\fP* __setUseUnderline (\fBalooWidget\fP * btn, gboolean yes)"

.SS "GtkButton* __toButtonGtk (\fBalooWidget\fP * wid)"

.SH "Variable Documentation"
.PP 
.SS "struct \fB_alooButton\fP Button\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
