.TH "include/utils/error.h" 3 "Tue Sep 3 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/utils/error.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBthrow_error\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void throw_error (const char * fmt,  \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
