.TH "include/builtin/grid.h" 3 "Tue Sep 3 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/builtin/grid.h \- Aloo Grid related functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br
\fC#include <gtk/gtk\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_alooGrid\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBalooWidget\fP * \fB__gridAttach\fP (\fBalooWidget\fP *grid, \fBalooWidget\fP *child, int column, int row, int width, int height)"
.br
.RI "Adds widget to aloo grid\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__gridAttachGtk\fP (\fBalooWidget\fP *grid, GtkWidget *child, int column, int row, int width, int height)"
.br
.RI "Adds widget to aloo grid\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__gridRemove\fP (\fBalooWidget\fP *grid, \fBalooWidget\fP *child)"
.br
.RI "Removes child from grid\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__gridRemoveGtk\fP (\fBalooWidget\fP *grid, GtkWidget *child)"
.br
.RI "Removes child from grid\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__alooGridNew\fP ()"
.br
.RI "Creates new Aloo Grid Widget\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__setGridColumnSpacing\fP (\fBalooWidget\fP *grid, int space)"
.br
.RI "Set the Grid Column Spacing\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__setGridRowSpacing\fP (\fBalooWidget\fP *grid, int space)"
.br
.RI "Set the Grid Row Spacing\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fB_alooGrid\fP \fBGrid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Aloo Grid related functions\&. 


.PP
\fBAuthor\fP
.RS 4
Jaipal001 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBalooWidget\fP* __alooGridNew ()"

.PP
Creates new Aloo Grid Widget\&. 
.PP
\fBReturns\fP
.RS 4
returns grid 
.RE
.PP

.SS "\fBalooWidget\fP* __gridAttach (\fBalooWidget\fP * grid, \fBalooWidget\fP * child, int column, int row, int width, int height)"

.PP
Adds widget to aloo grid\&. 
.PP
\fBParameters\fP
.RS 4
\fIgrid\fP grid in which child should be added 
.br
\fIchild\fP child to be added 
.br
\fIcolumn\fP column in which it should be added 
.br
\fIrow\fP row in which it should be added 
.br
\fIwidth\fP column span of widget or how many column it takes 
.br
\fIheight\fP row span of widget or how many row it takes 
.RE
.PP
\fBReturns\fP
.RS 4
returns grid back 
.RE
.PP

.SS "\fBalooWidget\fP* __gridAttachGtk (\fBalooWidget\fP * grid, GtkWidget * child, int column, int row, int width, int height)"

.PP
Adds widget to aloo grid\&. 
.PP
\fBParameters\fP
.RS 4
\fIgrid\fP grid in which child should be added 
.br
\fIchild\fP child to be added 
.br
\fIcolumn\fP column in which it should be added 
.br
\fIrow\fP row in which it should be added 
.br
\fIwidth\fP column span of widget or how many column it takes 
.br
\fIheight\fP row span of widget or how many row it takes 
.RE
.PP
\fBReturns\fP
.RS 4
returns grid back 
.RE
.PP

.SS "\fBalooWidget\fP* __gridRemove (\fBalooWidget\fP * grid, \fBalooWidget\fP * child)"

.PP
Removes child from grid\&. 
.PP
\fBReturns\fP
.RS 4
returns grid back 
.RE
.PP

.SS "\fBalooWidget\fP* __gridRemoveGtk (\fBalooWidget\fP * grid, GtkWidget * child)"

.PP
Removes child from grid\&. 
.PP
\fBReturns\fP
.RS 4
returns grid back 
.RE
.PP

.SS "\fBalooWidget\fP* __setGridColumnSpacing (\fBalooWidget\fP * grid, int space)"

.PP
Set the Grid Column Spacing\&. 
.SS "\fBalooWidget\fP* __setGridRowSpacing (\fBalooWidget\fP * grid, int space)"

.PP
Set the Grid Row Spacing\&. 
.SH "Variable Documentation"
.PP 
.SS "struct \fB_alooGrid\fP Grid\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
