.TH "include/label.h" 3 "Fri Aug 30 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/label.h
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBalooWidget\fP * \fBnewLabel\fP (const char *val)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBalooWidget\fP* newLabel (const char * val)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
