.TH "include/utils/logger.h" 3 "Tue Sep 3 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/utils/logger.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_logger\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB_logger\fP * \fBnewLogger\fP ()"
.br
.ti -1c
.RI "void \fB__aloo_log\fP (struct \fB_logger\fP *self, const char *message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __aloo_log (struct \fB_logger\fP * self, const char * message)"

.SS "struct \fB_logger\fP* newLogger ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
