.TH "include/style.h" 3 "Sun Sep 1 2024" "Version 1.0" "Aloo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/style.h \- Aloo CSS related functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_alooCSS\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fB__importCssFromPath_Type\fP) (const char *name)"
.br
.ti -1c
.RI "typedef void(* \fB__importCssFromData_Type\fP) (const char *content, gssize length)"
.br
.ti -1c
.RI "typedef void(* \fB__importCssFromFile_Type\fP) (GFile *file)"
.br
.ti -1c
.RI "typedef \fBalooWidget\fP *(* \fB__setWidth_Type\fP) (\fBalooWidget\fP *wid, int width)"
.br
.ti -1c
.RI "typedef \fBalooWidget\fP *(* \fB__setHeight_Type\fP) (\fBalooWidget\fP *wid, int height)"
.br
.ti -1c
.RI "typedef \fBalooWidget\fP *(* \fB__setSize_Type\fP) (\fBalooWidget\fP *wid, int width, int height)"
.br
.ti -1c
.RI "typedef \fBalooWidget\fP *(* \fB__widgetAddClass_Type\fP) (\fBalooWidget\fP *widget, char *class)"
.br
.ti -1c
.RI "typedef \fBalooWidget\fP *(* \fB__widgetRemoveClass_Type\fP) (\fBalooWidget\fP *widget, char *class)"
.br
.ti -1c
.RI "typedef char **(* \fB__getWidgetClasses_Type\fP) (\fBalooWidget\fP *widget)"
.br
.ti -1c
.RI "typedef \fBalooWidget\fP *(* \fB__setWidgetClasses_Type\fP) (\fBalooWidget\fP *widget, char **classes)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__importCssFromPath\fP (const char *name)"
.br
.RI "Import CSS file from path\&. "
.ti -1c
.RI "void \fB__importCssFromData\fP (const char *content, gssize length)"
.br
.RI "Import CSS file from content\&. "
.ti -1c
.RI "void \fB__importCssFromFile\fP (GFile *file)"
.br
.RI "Import CSS file from content\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__setWidth\fP (\fBalooWidget\fP *wid, int width)"
.br
.RI "Set the Width of widget\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__setHeight\fP (\fBalooWidget\fP *wid, int height)"
.br
.RI "Set the Height of widget\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__setSize\fP (\fBalooWidget\fP *wid, int width, int height)"
.br
.RI "Set the Width and Height of widget\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__widgetAddClass\fP (\fBalooWidget\fP *widget, char *class)"
.br
.RI "Adds class to widget\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__widgetRemoveClass\fP (\fBalooWidget\fP *widget, char *class)"
.br
.RI "Removes class from widget\&. "
.ti -1c
.RI "char ** \fBg__etWidgetClasses\fP (\fBalooWidget\fP *widget)"
.br
.RI "Gets classes of widget\&. "
.ti -1c
.RI "\fBalooWidget\fP * \fB__setWidgetClasses\fP (\fBalooWidget\fP *widget, char **classes)"
.br
.RI "Sets classes of widget\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fB_alooCSS\fP \fBCSS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Aloo CSS related functions\&. 


.PP
\fBAuthor\fP
.RS 4
Jaipal001 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef char**(* __getWidgetClasses_Type) (\fBalooWidget\fP *widget)"

.SS "typedef void(* __importCssFromData_Type) (const char *content, gssize length)"

.SS "typedef void(* __importCssFromFile_Type) (GFile *file)"

.SS "typedef void(* __importCssFromPath_Type) (const char *name)"

.SS "typedef \fBalooWidget\fP*(* __setHeight_Type) (\fBalooWidget\fP *wid, int height)"

.SS "typedef \fBalooWidget\fP*(* __setSize_Type) (\fBalooWidget\fP *wid, int width, int height)"

.SS "typedef \fBalooWidget\fP*(* __setWidgetClasses_Type) (\fBalooWidget\fP *widget, char **classes)"

.SS "typedef \fBalooWidget\fP*(* __setWidth_Type) (\fBalooWidget\fP *wid, int width)"

.SS "typedef \fBalooWidget\fP*(* __widgetAddClass_Type) (\fBalooWidget\fP *widget, char *class)"

.SS "typedef \fBalooWidget\fP*(* __widgetRemoveClass_Type) (\fBalooWidget\fP *widget, char *class)"

.SH "Function Documentation"
.PP 
.SS "void __importCssFromData (const char * content, gssize length)"

.PP
Import CSS file from content\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontent\fP css content 
.br
\fIlength\fP content length 
.RE
.PP

.SS "void __importCssFromFile (GFile * file)"

.PP
Import CSS file from content\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP CSS GFile 
.RE
.PP

.SS "void __importCssFromPath (const char * name)"

.PP
Import CSS file from path\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP path of css file 
.RE
.PP

.SS "\fBalooWidget\fP* __setHeight (\fBalooWidget\fP * wid, int height)"

.PP
Set the Height of widget\&. 
.SS "\fBalooWidget\fP* __setSize (\fBalooWidget\fP * wid, int width, int height)"

.PP
Set the Width and Height of widget\&. 
.SS "\fBalooWidget\fP* __setWidgetClasses (\fBalooWidget\fP * widget, char ** classes)"

.PP
Sets classes of widget\&. 
.SS "\fBalooWidget\fP* __setWidth (\fBalooWidget\fP * wid, int width)"

.PP
Set the Width of widget\&. 
.SS "\fBalooWidget\fP* __widgetAddClass (\fBalooWidget\fP * widget, char * class)"

.PP
Adds class to widget\&. 
.SS "\fBalooWidget\fP* __widgetRemoveClass (\fBalooWidget\fP * widget, char * class)"

.PP
Removes class from widget\&. 
.SS "char** g__etWidgetClasses (\fBalooWidget\fP * widget)"

.PP
Gets classes of widget\&. 
.SH "Variable Documentation"
.PP 
.SS "struct \fB_alooCSS\fP CSS\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aloo from the source code\&.
